# Generated by Django 3.2.6 on 2021-08-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=100)),
                ('respuestaCorrecta', models.CharField(max_length=40)),
                ('respuestaIncorrecta1', models.CharField(max_length=40)),
                ('respuestaIncorrecta2', models.CharField(max_length=40)),
            ],
        ),
    ]
